package com.hackcanada.claudecraft;

import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.client.MinecraftClient;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.nbt.*;
import net.minecraft.registry.Registries;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

public class SchematicHelper {

    /**
     * Place blocks from a JSON array sent by the server.
     * Each entry: {"x": int, "y": int, "z": int, "block":
     * "minecraft:stone[prop=val]"}
     * Coordinates are relative offsets — added to playerPos.
     */
    public static void placeBlocksFromJson(ServerWorld world, BlockPos playerPos, JsonArray blocks) {
        int placed = 0;
        for (JsonElement elem : blocks) {
            try {
                JsonObject blockObj = elem.getAsJsonObject();
                int x = blockObj.get("x").getAsInt();
                int y = blockObj.get("y").getAsInt();
                int z = blockObj.get("z").getAsInt();
                String blockStr = blockObj.get("block").getAsString();

                BlockState state = parseBlockState(blockStr);
                if (state != null) {
                    BlockPos pos = playerPos.add(x, y, z);
                    world.setBlockState(pos, state, Block.NOTIFY_ALL);
                    placed++;
                }
            } catch (Exception e) {
                ClaudeCraft.LOGGER.warn("Failed to place block: " + e.getMessage());
            }
        }
        ClaudeCraft.LOGGER.info("Placed " + placed + " blocks in this layer");
    }

    /**
     * Parse a block string like "minecraft:oak_stairs[facing=east,half=bottom]"
     * into a BlockState.
     */
    private static BlockState parseBlockState(String blockStr) {
        String blockId;
        String propsStr = null;

        // Split block ID and properties
        int bracketIdx = blockStr.indexOf('[');
        if (bracketIdx >= 0) {
            blockId = blockStr.substring(0, bracketIdx);
            propsStr = blockStr.substring(bracketIdx + 1, blockStr.length() - 1);
        } else {
            blockId = blockStr;
        }

        // Look up the block in the registry
        Block block = Registries.BLOCK.get(Identifier.of(blockId));
        if (block == null) {
            ClaudeCraft.LOGGER.warn("Unknown block: " + blockId);
            return null;
        }

        BlockState state = block.getDefaultState();

        // Apply properties if present
        if (propsStr != null && !propsStr.isEmpty()) {
            for (String prop : propsStr.split(",")) {
                String[] kv = prop.split("=", 2);
                if (kv.length == 2) {
                    net.minecraft.state.property.Property<?> property = block.getStateManager().getProperty(kv[0]);
                    if (property != null) {
                        state = applyProperty(state, property, kv[1]);
                    }
                }
            }
        }

        return state;
    }

    @SuppressWarnings("unchecked")
    private static <T extends Comparable<T>> BlockState applyProperty(
            BlockState state, net.minecraft.state.property.Property<T> property, String valueStr) {
        return property.parse(valueStr).map(value -> state.with(property, value)).orElse(state);
    }

    public static void saveLitematica(World world, BlockPos pos1, BlockPos pos2, String filename) {
        int minX = Math.min(pos1.getX(), pos2.getX());
        int minY = Math.min(pos1.getY(), pos2.getY());
        int minZ = Math.min(pos1.getZ(), pos2.getZ());
        int maxX = Math.max(pos1.getX(), pos2.getX());
        int maxY = Math.max(pos1.getY(), pos2.getY());
        int maxZ = Math.max(pos1.getZ(), pos2.getZ());

        int sizeX = maxX - minX + 1;
        int sizeY = maxY - minY + 1;
        int sizeZ = maxZ - minZ + 1;

        NbtCompound root = new NbtCompound();
        root.putInt("MinecraftDataVersion", 3953);
        root.putInt("Version", 6);

        NbtCompound metadata = new NbtCompound();
        metadata.putString("Author", "Litemod");
        metadata.putString("Description", "Generated by Litemod");
        metadata.putString("Name", filename);
        metadata.putLong("TimeCreated", System.currentTimeMillis());
        metadata.putLong("TimeModified", System.currentTimeMillis());

        NbtCompound enclosingSize = new NbtCompound();
        enclosingSize.putInt("x", sizeX);
        enclosingSize.putInt("y", sizeY);
        enclosingSize.putInt("z", sizeZ);
        metadata.put("EnclosingSize", enclosingSize);
        metadata.putInt("TotalBlocks", sizeX * sizeY * sizeZ);
        metadata.putInt("TotalVolume", sizeX * sizeY * sizeZ);
        root.put("Metadata", metadata);

        NbtCompound regions = new NbtCompound();
        NbtCompound region = new NbtCompound();

        NbtCompound position = new NbtCompound();
        position.putInt("x", 0);
        position.putInt("y", 0);
        position.putInt("z", 0);
        region.put("Position", position);

        NbtCompound size = new NbtCompound();
        size.putInt("x", sizeX);
        size.putInt("y", sizeY);
        size.putInt("z", sizeZ);
        region.put("Size", size);

        List<BlockState> paletteList = new ArrayList<>();
        int[] indices = new int[sizeX * sizeY * sizeZ];
        int index = 0;

        for (int y = 0; y < sizeY; y++) {
            for (int z = 0; z < sizeZ; z++) {
                for (int x = 0; x < sizeX; x++) {
                    BlockPos current = new BlockPos(minX + x, minY + y, minZ + z);
                    BlockState state = world.getBlockState(current);
                    if (!paletteList.contains(state)) {
                        paletteList.add(state);
                    }
                    indices[index++] = paletteList.indexOf(state);
                }
            }
        }

        NbtList blockStatePalette = new NbtList();
        for (BlockState state : paletteList) {
            String name = net.minecraft.registry.Registries.BLOCK.getId(state.getBlock()).toString();
            NbtCompound blockCmp = new NbtCompound();
            blockCmp.putString("Name", name);
            blockStatePalette.add(blockCmp);
        }
        region.put("BlockStatePalette", blockStatePalette);

        int bitsPerEntry = Math.max(2, Integer.SIZE - Integer.numberOfLeadingZeros(paletteList.size() - 1));
        long[] packedArray = packBits(indices, bitsPerEntry);
        region.putLongArray("BlockStates", packedArray);

        region.put("Entities", new NbtList());
        region.put("PendingBlockTicks", new NbtList());
        region.put("PendingFluidTicks", new NbtList());
        region.put("TileEntities", new NbtList());

        regions.put(filename, region);
        root.put("Regions", regions);

        try {
            File dir = new File(MinecraftClient.getInstance().runDirectory, "litematics");
            dir.mkdirs();
            File file = new File(dir, filename + ".litematic");
            NbtIo.writeCompressed(root, file.toPath());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static long[] packBits(int[] indices, int bitsPerEntry) {
        long[] result = new long[(indices.length * bitsPerEntry + 63) / 64];
        for (int i = 0; i < indices.length; i++) {
            int value = indices[i];
            int bitIndex = i * bitsPerEntry;
            int longIndex = bitIndex / 64;
            int bitOffset = bitIndex % 64;

            result[longIndex] = result[longIndex] | (((long) value) << bitOffset);
            if (bitOffset + bitsPerEntry > 64 && longIndex + 1 < result.length) {
                result[longIndex + 1] = result[longIndex + 1] | (((long) value) >>> (64 - bitOffset));
            }
        }
        return result;
    }

    public static void loadLitematica(World world, BlockPos origin, String filename) {
        try {
            ClaudeCraft.LOGGER
                    .info("Attempting to load schematic: " + filename + " at " + origin);
            File dir = new File(MinecraftClient.getInstance().runDirectory, "litematics");
            File file = new File(dir, filename + ".litematic");

            if (!file.exists()) {
                ClaudeCraft.LOGGER.warn("Schematic file does not exist: " + file.getAbsolutePath());
                return;
            }

            MinecraftClient.getInstance().execute(() -> {
                try {
                    // 1. Load the schematic from disk
                    fi.dy.masa.litematica.schematic.LitematicaSchematic schematic = fi.dy.masa.litematica.schematic.LitematicaSchematic
                            .createFromFile(
                                    dir.toPath(), filename);

                    if (schematic == null) {
                        ClaudeCraft.LOGGER.warn("Failed to parse schematic file: " + filename);
                        return;
                    }

                    ClaudeCraft.LOGGER.info("Loaded schematic: " + filename
                            + " with " + schematic.getSubRegionCount() + " regions");

                    // 2. Create a placement at the player's position
                    fi.dy.masa.litematica.schematic.placement.SchematicPlacement placement = fi.dy.masa.litematica.schematic.placement.SchematicPlacement
                            .createFor(
                                    schematic, origin, filename, true, true);

                    // 3. Register the placement with Litematica's manager
                    fi.dy.masa.litematica.data.DataManager
                            .getSchematicPlacementManager()
                            .addSchematicPlacement(placement, true);

                    // 4. Switch to PASTE_SCHEMATIC tool so the stick becomes the paste wand
                    fi.dy.masa.litematica.data.DataManager
                            .setToolMode(fi.dy.masa.litematica.tool.ToolMode.PASTE_SCHEMATIC);

                    // 5. Give the player a stick in their main hand if they don't have one,
                    //    because Litematica's default tool item is a stick.
                    MinecraftClient mc2 = MinecraftClient.getInstance();
                    if (mc2.player != null) {
                        ItemStack held = mc2.player.getMainHandStack();
                        if (held.isEmpty() || held.getItem() != Items.STICK) {
                            // Find an existing stick in the hotbar first
                            boolean found = false;
                            for (int slot = 0; slot < 9; slot++) {
                                ItemStack s = mc2.player.getInventory().getStack(slot);
                                if (s.getItem() == Items.STICK) {
                                    mc2.player.getInventory().swapSlotWithHotbar(slot);
                                    found = true;
                                    break;
                                }
                            }
                            // If no stick in hotbar, put one in the current slot
                            if (!found) {
                                int sel = mc2.player.getInventory().getSlotWithStack(
                                        new ItemStack(Items.STICK));
                                if (sel < 0) {
                                    // No stick anywhere — inject one into slot 0
                                    mc2.player.getInventory().setStack(0, new ItemStack(Items.STICK));
                                    mc2.player.getInventory().swapSlotWithHotbar(0);
                                }
                            }
                        }
                        mc2.player.sendMessage(
                            net.minecraft.text.Text.literal(
                                "§a[ClaudeCraft] Schematic loaded! §eRight-click with your stick to paste."),
                            false);
                    }

                    ClaudeCraft.LOGGER.info("Schematic placement added and tool set to PASTE_SCHEMATIC!");
                } catch (Exception ex) {
                    ClaudeCraft.LOGGER.error("Litematica API exception", ex);
                }
            });

        } catch (Exception e) {
            ClaudeCraft.LOGGER.error("Failed to load schematic", e);
            e.printStackTrace();
        }
    }

    @SuppressWarnings("unchecked")
    private static <T extends Comparable<T>> BlockState parseAndSetPropertyValue(BlockState state,
            net.minecraft.state.property.Property<T> property, String valueStr) {
        return property.parse(valueStr).map(value -> state.with(property, value)).orElse(state);
    }
}
