package com.hackcanada.litematicmod;

import net.minecraft.block.BlockState;
import net.minecraft.client.MinecraftClient;
import net.minecraft.nbt.*;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;

public class LitematicaHelper {

    public static void saveLitematica(World world, BlockPos pos1, BlockPos pos2, String filename) {
        int minX = Math.min(pos1.getX(), pos2.getX());
        int minY = Math.min(pos1.getY(), pos2.getY());
        int minZ = Math.min(pos1.getZ(), pos2.getZ());
        int maxX = Math.max(pos1.getX(), pos2.getX());
        int maxY = Math.max(pos1.getY(), pos2.getY());
        int maxZ = Math.max(pos1.getZ(), pos2.getZ());

        int sizeX = maxX - minX + 1;
        int sizeY = maxY - minY + 1;
        int sizeZ = maxZ - minZ + 1;

        NbtCompound root = new NbtCompound();
        root.putInt("MinecraftDataVersion", 3953);
        root.putInt("Version", 6);

        NbtCompound metadata = new NbtCompound();
        metadata.putString("Author", "Litemod");
        metadata.putString("Description", "Generated by Litemod");
        metadata.putString("Name", filename);
        metadata.putLong("TimeCreated", System.currentTimeMillis());
        metadata.putLong("TimeModified", System.currentTimeMillis());

        NbtCompound enclosingSize = new NbtCompound();
        enclosingSize.putInt("x", sizeX);
        enclosingSize.putInt("y", sizeY);
        enclosingSize.putInt("z", sizeZ);
        metadata.put("EnclosingSize", enclosingSize);
        metadata.putInt("TotalBlocks", sizeX * sizeY * sizeZ);
        metadata.putInt("TotalVolume", sizeX * sizeY * sizeZ);
        root.put("Metadata", metadata);

        NbtCompound regions = new NbtCompound();
        NbtCompound region = new NbtCompound();

        NbtCompound position = new NbtCompound();
        position.putInt("x", 0);
        position.putInt("y", 0);
        position.putInt("z", 0);
        region.put("Position", position);

        NbtCompound size = new NbtCompound();
        size.putInt("x", sizeX);
        size.putInt("y", sizeY);
        size.putInt("z", sizeZ);
        region.put("Size", size);

        List<BlockState> paletteList = new ArrayList<>();
        int[] indices = new int[sizeX * sizeY * sizeZ];
        int index = 0;

        for (int y = 0; y < sizeY; y++) {
            for (int z = 0; z < sizeZ; z++) {
                for (int x = 0; x < sizeX; x++) {
                    BlockPos current = new BlockPos(minX + x, minY + y, minZ + z);
                    BlockState state = world.getBlockState(current);
                    if (!paletteList.contains(state)) {
                        paletteList.add(state);
                    }
                    indices[index++] = paletteList.indexOf(state);
                }
            }
        }

        NbtList blockStatePalette = new NbtList();
        for (BlockState state : paletteList) {
            String name = net.minecraft.registry.Registries.BLOCK.getId(state.getBlock()).toString();
            NbtCompound blockCmp = new NbtCompound();
            blockCmp.putString("Name", name);
            blockStatePalette.add(blockCmp);
        }
        region.put("BlockStatePalette", blockStatePalette);

        int bitsPerEntry = Math.max(2, Integer.SIZE - Integer.numberOfLeadingZeros(paletteList.size() - 1));
        long[] packedArray = packBits(indices, bitsPerEntry);
        region.putLongArray("BlockStates", packedArray);

        region.put("Entities", new NbtList());
        region.put("PendingBlockTicks", new NbtList());
        region.put("PendingFluidTicks", new NbtList());
        region.put("TileEntities", new NbtList());

        regions.put(filename, region);
        root.put("Regions", regions);

        try {
            File dir = new File(MinecraftClient.getInstance().runDirectory, "litematics");
            dir.mkdirs();
            File file = new File(dir, filename + ".litematic");
            NbtIo.writeCompressed(root, file.toPath());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static long[] packBits(int[] indices, int bitsPerEntry) {
        int valuesPerLong = 64 / bitsPerEntry;
        long[] result = new long[(indices.length + valuesPerLong - 1) / valuesPerLong];
        long currentLong = 0;
        int currentBit = 0;
        int longIndex = 0;

        for (int value : indices) {
            if (currentBit + bitsPerEntry > 64) {
                result[longIndex++] = currentLong;
                currentLong = 0;
                currentBit = 0;
            }
            currentLong |= ((long) value & ((1L << bitsPerEntry) - 1)) << currentBit;
            currentBit += bitsPerEntry;
        }
        if (currentBit > 0) {
            result[longIndex] = currentLong;
        }
        return result;
    }

    public static void loadLitematica(World world, BlockPos origin, String filename) {
        try {
            File dir = new File(MinecraftClient.getInstance().runDirectory, "litematics");
            File file = new File(dir, filename + ".litematic");
            if (!file.exists())
                return;

            NbtCompound root = NbtIo.readCompressed(file.toPath(), net.minecraft.nbt.NbtSizeTracker.ofUnlimitedBytes());
            NbtCompound regions = root.getCompound("Regions").orElse(null);
            if (regions == null || regions.isEmpty())
                return;

            String regionName = regions.getKeys().iterator().next();
            NbtCompound region = regions.getCompound(regionName).orElse(null);

            NbtCompound size = region.getCompound("Size").orElse(null);
            int sizeX = size.getInt("x").orElse(0);
            int sizeY = size.getInt("y").orElse(0);
            int sizeZ = size.getInt("z").orElse(0);

            NbtList paletteTag = region.getList("BlockStatePalette").orElse(null);
            BlockState[] palette = new BlockState[paletteTag.size()];
            for (int i = 0; i < paletteTag.size(); i++) {
                NbtCompound blockTag = paletteTag.getCompound(i).orElse(null);
                String name = blockTag.getString("Name").orElse("");
                net.minecraft.util.Identifier id = net.minecraft.util.Identifier.of(name);
                net.minecraft.block.Block block = net.minecraft.registry.Registries.BLOCK.get(id);
                palette[i] = block.getDefaultState();
            }

            long[] blockStates = region.getLongArray("BlockStates").orElse(new long[0]);
            int bitsPerEntry = Math.max(2, Integer.SIZE - Integer.numberOfLeadingZeros(palette.length - 1));

            int valuesPerLong = 64 / bitsPerEntry;
            long mask = (1L << bitsPerEntry) - 1;

            int i = 0;
            for (int y = 0; y < sizeY; y++) {
                for (int z = 0; z < sizeZ; z++) {
                    for (int x = 0; x < sizeX; x++) {
                        int longIndex = i / valuesPerLong;
                        int bitOffset = (i % valuesPerLong) * bitsPerEntry;
                        int paletteIndex = (int) ((blockStates[longIndex] >>> bitOffset) & mask);

                        BlockState state = palette[paletteIndex];
                        world.setBlockState(origin.add(x, y, z), state);
                        i++;
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
